# Heating system (gas heated house) ----------------
gas_furnace <- function(eta_low,
                        eta_high,
                        annual_gas_heating, # consumption in CCF
                        square_footage,
                        heating_degree_hours,
                        gas_price,
                        typical_heating_system_price,
                        high_efficiency_heating_system_price){
  # Description:
  # gas_furnace() is function that could help to calculate the energy consumption after change into the high efficiency heating system for gas heated house
  # By using this function,
  # 1) the annual energy consumption by using high efficiency heating system could be obtained
  # 2) the annual energy consumption saving for using the high efficiency heating system could be obtained
  # 3) payback years for using high efficiency heating system
  # 4) energy consumption intensity on unit square footage

  # Arguments:
  # Input:
  #   eta_low: efficiency value for low efficiency heating system
  #   eta_high: efficiency value for high efficiency heating system
  #   annual_gas_heating: residential annual gas heating without changing the heating efficiency (CCF)
  #   square_footage: square footage for residential house
  #   heating degree hours: heating degree hours that generated by using HDH function
  #   gas_price : natural gas price for local area
  #   typical_heating_system_price: price for low efficiency (typical heating) system (USD)
  #   high_efficiency_system_price: price for high efficiency system (USD)


  # Output:
  #   heating_U_value: Byproduct
  #   annual_gas_heating_high_efficiency: annual gas consumption after change into high efficiency heating system (CCF)
  #   annual_gas_heating_saving: annual gas consumption saving after change into high efficiency heating system (CCF)
  #   annual_gas_heating_USD: annual gas heating consumption saving convert into USD dollars (USD)
  #   normalized gas heating eta change: heating consumption intensity after change the efficiency
  #   high_efficiency_heating_system_payback: the payback years for installing the high efficiency heating system (yr)



  # dynamic U_value (unit kWh / K)
  # the calculated result for U_value is exactly the U_value as insulation value
  # the calculation for U_value is based on the calculation equation
  # equation:
  # E_H <- (T_in - T_out) / eta_H * UAa * hr_H
  # ------>
  # E_H <- HDH / eta_H * UAa

  heating_U_value <- annual_gas_heating * 10 ^ 5 / 3413 * eta_low / heating_degree_hours # convert CCF to kWh,

  # annual gas consumption change by increase the efficiency of heating system
  # annual_gas_heating with high efficiency saving
  annual_gas_heating_high_efficiency_saving <- abs(- heating_degree_hours / (eta_low ^ 2) * (eta_high - eta_low) * heating_U_value) # unit kWh

  # convert annual_gas_heating_high_efficiency from kWh into CCF
  # Note:
  # could add unit option for future
  annual_gas_heating_high_efficiency_saving <- annual_gas_heating_high_efficiency_saving * 3413 / 10 ^ 5 # unit CCF
  # annual heating saving in USD with high efficiency heating
  annual_gas_heating_saving_USD <- annual_gas_heating_high_efficiency_saving * gas_price

  # annual gas heating consumption with high efficiency system
  annual_gas_heating_high_efficiency <- annual_gas_heating - annual_gas_heating_high_efficiency_saving # unit CCF

  # normalized gas heating with efficiency change
  normalized_gas_heating_eta_change <-  annual_gas_heating_high_efficiency / square_footage

  # payback for installing high efficiency heating system
  high_efficiency_heating_system_payback <- (high_efficiency_heating_system_price - typical_heating_system_price) / annual_gas_heating_saving_USD

  # Unlike python, there is no way to return() multiple values by using 1 function
  # the list has to be created in order to generate multiple output at the same time
  high_efficiency_gas_heating_list <- list(heating_U_value,
                                           annual_gas_heating_high_efficiency_saving,
                                           annual_gas_heating_high_efficiency,
                                           annual_gas_heating_saving_USD,
                                           normalized_gas_heating_eta_change,
                                           high_efficiency_heating_system_payback)
  # output value
  return(high_efficiency_gas_heating_list)

}

